import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Roboto_Condensed, Urbanist } from "next/font/google";
import "./globals.css";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={robotoCondensed.className}>
      <body>{children}</body>
    </html>
  );
}
